<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: dzliu
 * Date: Tue, 18 Feb 2014 07:56:50 +0000
 */

$conf['title'] = 'WIKI-1054';
$conf['template'] = 'taratasy';
$conf['license'] = '0';
$conf['baseurl'] = 'https://wiki-1054.rhcloud.com';
$conf['fullpath'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['userewrite'] = '1';
$conf['fnencode'] = 'utf-8';
$conf['autoplural'] = 1;
$conf['proxy']['ssl'] = 1;
$conf['plugin']['authmysql']['server'] = 'mysql://$OPENSHIFT_MYSQL_DB_HOST:$OPENSHIFT_MYSQL_DB_PORT/';
$conf['plugin']['authmysql']['user'] = 'adminb5RWNMW';
$conf['plugin']['authmysql']['password'] = '3gP5CttFNK9M';
$conf['plugin']['authmysql']['database'] = 'wiki';
$conf['plugin']['authmysql']['debug'] = '1';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['plugin']['backup']['filterbackups'] = 1;
$conf['tpl']['prsnl10']['prsnl10_headernav'] = '1';
$conf['tpl']['prsnl10']['prsnl10_headernav_location'] = ':wiki:navigation';
$conf['tpl']['prsnl10']['prsnl10_copyright'] = '1';
$conf['tpl']['prsnl10']['prsnl10_copyright_default'] = '1';
$conf['tpl']['prsnl10']['prsnl10_footer'] = '0';
$conf['tpl']['prsnl10']['prsnl10_footer_location'] = '!!not set!!';
$conf['tpl']['prsnl10']['prsnl10_showpageinfo'] = '1';
$conf['tpl']['prsnl10']['prsnl10_hideadminlinksfromanon'] = '1';
$conf['tpl']['prsnl10']['prsnl10_loaduserjs'] = '1';

// end auto-generated content
